### ISSUE TITLE
Is it possible to install GSI lineage-19.0 through this recovery? 

### ISSUE THREAD

**Issue by xFat1** [AndyCGYan/android_device_realme_RE546F#1]
Is it possible to install your GSI lineage-19.0 through this recovery on Realme GT Master Explorer Edition stock rom 12C.03?

**Comment by xFat1** [comment]
In fastboot mode:
`fastboot boot lineage-19.0-20211201-recovery-RE546F.img` - works. It is possible to boot into the recovery.

`fastboot flash recovery lineage-19.0-20211201-recovery-RE546F.img`
`fastboot reboot fastboot`
The phone shuts down. It won't boot into the new recovery.

**Comment by AndyCGYan** [comment]
I run my own LOS19 GSI on this device - this recovery is made for just this purpose.
This has only been tested with C.02 base. Did you disable verity / flash vbmeta?

**Comment by xFat1** [comment]
I got the stock firmware RUI_3.0_12_rmx3366_11_C.03 after OTA update.
I don't have a stock firmware file to extract boot.img and vbmeta.img from.

**Comment by xFat1** [comment]
> I run my own LOS19 GSI on this device

@AndyCGYan 
Can you share a brief instruction on how to properly flash your LOS19 GSI on this device?
lack the qualifications to understand all the intricacies myself😔

**Comment by AndyCGYan** [comment]
- Flash Lineage Recovery and [Google vbmeta](https://dl.google.com/developers/android/qt/images/gsi/vbmeta.img)
- Immediately enter recovery with key selection
- Enter fastbootd
- `fastboot flash system xxx.img`
- Return to recovery
- Format data, reboot

Just GSI basics, apart from the need for a custom recovery.
